[project]
name = "cibot-test"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cibot",
]

[tool.uv.sources]
cibot = { git = "https://github.com/nrbnlulu/cibot.git", branch = "wip" }
