name: Cibot
on: 
  pull_request:
  push:
    branches:
    - main
    - master
jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          python-version: "3.12"
      
      - name: Run cibot
        env:
          CIBOT_GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          CIBOT_GITHUB_REPO_SLUG: ${{ github.repository }}
          CIBOT_BACKEND: github
          CIBOT_STORAGE: github_issue
          CIBOT_STORAGE_GH_ISSUE_NUMBER: 2

        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            uv run cibot on-pr-changed ${{ github.event.number }} --plugin deferred_release --plugin semver
          elif [ "${{ github.event_name }}" == "push" ]; then
            uv run cibot on-commit-to-main --plugin deferred_release --plugin semver
          fi