name: Cibot
on:
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  deferred_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOT_TOKEN }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          python-version: "3.12"

      - name: Run cibot
        env:
          CIBOT_GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          CIBOT_GITHUB_REPO_SLUG: ${{ github.repository }}
          CIBOT_BACKEND: github
          CIBOT_STORAGE: github_issue
          CIBOT_STORAGE_GH_ISSUE_NUMBER: 2

        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            uv run cibot on-pr-changed ${{ github.event.number }} --plugin deferred_release --plugin semver
          elif [ "${{ github.event_name }}" == "push" ]; then
            uv run cibot on-commit-to-main --plugin deferred_release --plugin semver
          fi
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          python-version: "3.12"
      - name: Run tests
        run: |
          uv run pytest --cov=src --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: coverage-file
          path: coverage.xml

  cov-report:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'pull_request'

    steps:
      # trick for diff-cover https://github.com/Bachmann1234/diff_cover/issues/55#issuecomment-817373173
      - name: checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Make ${{ github.base_ref }} branch exist
        run: |
          git checkout -b ${{ github.base_ref }} --track origin/${{ github.base_ref }}
          git checkout -

      - uses: actions/download-artifact@v4
        with:
          name: coverage-file

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          python-version: "3.12"

      - name: Run cibot coverage comment
        env:
          CIBOT_GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          CIBOT_GITHUB_REPO_SLUG: ${{ github.repository }}
          CIBOT_BACKEND: github
          CIBOT_STORAGE: github_issue
          CIBOT_STORAGE_GH_ISSUE_NUMBER: 2
          DIFF_COV_COMPARE_BRANCH: master

        run: |
          uv run cibot on-pr-changed ${{ github.event.number }}  --plugin diffcov
